
services:
  mysql:
    image: mysql:8
    container_name: mysql_shared
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springboot
    ports:
      - "3307:3306"  # MySQL теперь доступен на стандартном порту 3306
    volumes:
      - mysql_data:/var/lib/mysql

  app_one:
    build:
      context: .
      args:
        VERSION: 0.0.1-SNAPSHOT
    container_name: springboot_app_one
#    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: docker-one  # Активируем профиль "docker-one"
      SERVER_PORT: 8080
#      MYSQL_HOST: mysql
#      MYSQL_PORT: 3306
    ports:
      - "8080:8080"

  app_two:
    build:
      context: .
      args:
        VERSION: 0.0.1-SNAPSHOT
    container_name: springboot_app_two
#    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: docker-two  # Активируем профиль "docker-two"
      SERVER_PORT: 8080
#      MYSQL_HOST: mysql
#      MYSQL_PORT: 3306
    ports:
      - "8081:8080"

volumes:
  mysql_data: