version: '3.9'

services:
  postgres-db:
    image: postgres:17.2
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    container_name: postgresql_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db-network

  mysql:
    image: mysql:8.0
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_boot_database
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - db-network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - db-network

volumes:
  mysql-data: {}
  postgres-data: {}

networks:
  db-network:
    driver: bridge


