version: "3.8"
name: spring_boot_app_docker_two

services:
  mysql:
    image: mysql:8
    container_name: mysql_container_two
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springboot
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:

    build:
      args:
        VERSION: 0.0.1-SNAPSHOT
    container_name: springboot_app_two
    restart: always
    depends_on:
      - mysql
    environment:
      SERVER_PORT: 8081
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306  # Внутри контейнера MySQL остается на 3306
    ports:
      - "8081:8080"

volumes:
  mysql_data: