-- liquibase formatted sql
-- changeset player:1
insert into player (age, name)
values (30, 'messi'),
       (59, 'Maradonna'),
       (35, 'Antonio'),
       (35, 'Henry'),
       (null, 'Leonardo'),
       (null, 'Jamal'),
       (null, 'Rafinha'),
       (null, 'Vinchenso'),
       (null, 'Carvalho'),
       (null, 'Narut'),
       (null, 'Carlos'),
       (null, 'Ibrahimovich'),
       (null, 'Lewandovsky'),
       (null, 'Pepe'),
       (null, 'Higuain'),
       (null, 'Pogba'),
       (null, 'Griezmann'),
       (null, 'Silva'),
       (null, 'Modric'),
       (null, 'Ramos'),
       (null, 'Cortois'),
       (null, 'Ozil'),
       (null, 'Aguero'),
       (null, 'Ronaldinho'),
       (null, 'Raul');