server:
  port: 8081
  servlet:
    session:
      timeout: 15m
      cookie:
        name: JSESSIONID_DEV
spring:
  datasource:
    url: jdbc:mysql://mysql_db:3306/springboot?createDatabaseIfNotExist=true
    username: root
    password: root
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
    logging:
      level:
        org:
          springframework:
            security: DEBUG
  application:
    settings:
      pageSize: 10
  jpa:
    properties:
      hbm2ddl:
        auto: validate
      show_sql: true
  liquibase:
    change-log: classpath:db/changelog/liquibase-changeLog.yaml
    enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG

  console:
    encoding: UTF-8