server:
  port: ${SERVER_PORT:8080}
  servlet:
    session:
      timeout: 15m
#      cookie:
#        name: JSESSIONID_ONE

spring:
  datasource:
    url: jdbc:mysql://mysql_shared:3306/springboot?createDatabaseIfNotExist=true
#    url: jdbc:mysql://localhost:3307/springboot?createDatabaseIfNotExist=true
    username: root
    password: root
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    settings:
      pageSize: 10

  jpa:
    properties:
      hbm2ddl:
        auto: validate
      show_sql: true
  liquibase:
    change-log: classpath:db/changelog/liquibase-changeLog.yaml
    enabled: true
