server:
  port: 8082
  servlet:
    session:
      timeout: 15m
#      cookie:
#        name: JSESSIONID_LOCALE

spring:
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3307/springboot?createDatabaseIfNotExist=true
    username: root
    password: root
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    settings:
      pageSize: 10

    logging:
      level:
        org:
          springframework:
            security: INFO
  jpa:
    properties:
      hbm2ddl:
        auto: validate
      show_sql: true
  liquibase:
    change-log: classpath:db/changelog/liquibase-changeLog.yaml
    enabled: true
